---

- hosts: dev
  tasks:
  - name: Testing hostsfile
    hostsfile: hostname=dev.local ip_address=127.0.0.10 comment="dev machine"

  - name: Adding devbox to hostsfile
    hostsfile: hostname=devbox ip_address=127.0.0.2 aliases=devbox.local comment="devbox"

  - name: adding dbsrv to hostsfile
    hostsfile: hostname=dbsrv ip_address=127.0.0.4 aliases=dbsrv.local comment="dev machine"

  - name: adding caching hostsfile
    hostsfile: hostname=cache-svr ip_address=127.0.0.5 aliases=cache-svr.local comment="dev machine"
